# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.xci
# IP: The module: 'dsi_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.xci
# IP: The module: 'dsi_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
