# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug.xci
# IP: The module: 'dsi_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_debug'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug.xci
# IP: The module: 'dsi_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsi_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
