# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo.xci
# IP: The module: 'video_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo/video_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo/video_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo.xci
# IP: The module: 'video_data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo/video_data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo/video_data_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
