# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.cache/wt [current_project]
set_property parent.project_path /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/dave/ip/dsi-lcd-ctrl/init-rom-gen/disp_config_rom.coe
add_files -quiet /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_pll/video_pll.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_pll/video_pll.dcp]
add_files -quiet /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/video_data_fifo/video_data_fifo.dcp]
add_files -quiet /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/init_config_rom/init_config_rom.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/init_config_rom/init_config_rom.dcp]
add_files -quiet /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_debug/dsi_debug.dcp]
add_files -quiet /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/sources_1/ip/dsi_pll/dsi_pll.dcp]
read_vhdl -library xil_defaultlib {
  /home/dave/ip/dsi-tx/dsi_tx_rgb_to_word.vhd
  /home/dave/ip/dsi-tx/dsi_tx_prepend_dcs_cmd.vhd
  /home/dave/ip/dsi-tx/dsi_tx_payload_crc.vhd
  /home/dave/ip/dsi-tx/dsi_tx_header_ecc.vhd
  /home/dave/ip/dsi-lcd-ctrl/lcd_init_cmd_ctrl.vhd
  /home/dave/ip/dsi-tx/dsi_tx_wordclk_div.vhd
  /home/dave/ip/dsi-tx/dsi_tx_packetiser.vhd
  /home/dave/ip/dsi-tx/dsi_tx_lp_lane_ctrl.vhd
  /home/dave/ip/dsi-tx/dsi_tx_lpdt_tx.vhd
  /home/dave/ip/dsi-tx/dsi_tx_hs_tx_phy.vhd
  /home/dave/ip/dsi-tx/dsi_tx_cmd_mode_controller.vhd
  /home/dave/ip/dsi-tx/dsi_tx_clock_phy.vhd
  /home/dave/ip/video-misc/video_timing_ctrl.vhd
  /home/dave/ip/video-misc/video_splitter.vhd
  /home/dave/ip/dsi-lcd-ctrl/lcd_pwr_seq_ctrl.vhd
  /home/dave/ip/dsi-tx/dsi_tx_cmd_mode_top.vhd
  /home/dave/ip/video-misc/test_pattern_enhanced.vhd
  /home/dave/ip/dsi-tx/dsi_tx_dual_dsi_top.vhd
  /home/dave/ip/demo-top/z5p_lcd_1080p_demo.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/dave/ip/examples/z5p_lcd_1080p/z5p_lcd_1080p.srcs/constrs_1/new/constraints.xdc]


synth_design -top z5p_lcd_1080p_demo -part xc7k325tffg900-2


write_checkpoint -force -noxdef z5p_lcd_1080p_demo.dcp

catch { report_utilization -file z5p_lcd_1080p_demo_utilization_synth.rpt -pb z5p_lcd_1080p_demo_utilization_synth.pb }
